name: Deploy API

on:
  push:
    paths:
      - "workers/api/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install deps
        run: pnpm install

      - name: Deploy to Cloudflare
        run: pnpm --filter @parthub/api exec wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
